[mypy]
files = lib/**/*.py,tests/**/*.py
allow_redefinition = True

# We use class properties, which mypy considers an error, probably because it's going to be deprecated.
# Ignore that for now.
disable_error_code = misc 

# This part of the code will need some work before it'll start passing.
[mypy-lib.tartan.*]
ignore_errors = True

# These libraries are missing type information
[mypy-colormath2.*]
ignore_missing_imports = True

[mypy-pyembroidery.*]
ignore_missing_imports = True