#!/bin/bash
set -e
inkstitch_folder=($HOME/Library/Application\ Support/org.inkscape.Inkscape/config/inkscape/extensions/inkstitch)
if [[ -L "${inkstitch_folder}" ]]; then
	unlink "${inkstitch_folder}"
	echo "Unlinking manual install, to avoid damaging user local repository."
else
	rm -rf "${inkstitch_folder}"
	echo "Removing previous Ink/Stitch installation."
fi
exit 0
