name: Build
on:
  push:
    branches-ignore:
      - master
      - main
    tags:
      - "v*.*.*"
  workflow_dispatch:
      inputs:
          TEST_SIGNING:
              description: 'Sign windows binaries'
              required: true
              type: boolean
              default: false
jobs:
  linux64:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - uses: actions/setup-python@v6
        with:
          python-version: '3.11.x'
          cache: 'pip'
      - name: install dependencies
        shell: bash
        run: |
          sudo apt-get update
          sudo gem install fpm
          python -m pip install --upgrade pip
          python -m pip install wheel

          sudo apt-get install gettext

          # for wxPython
          sudo apt install libnotify4
          sudo apt install glib-networking libsdl2-dev libsdl2-2.0-0

          # for PyGObject
          sudo apt install libgirepository1.0-dev libcairo2-dev

          # for shapely
          sudo apt install build-essential libgtk-3-dev cmake

          # for numpy
          sudo apt install  gfortran libopenblas-dev liblapack-dev pkg-config

          uname -a
          python --version
          python -m pip --version
          python -m pip debug

          python -m pip install pycairo
          python -m pip install PyGObject==3.50.0
          python -m pip install numpy --no-binary numpy

          python -m pip install https://github.com/inkstitch/build-libs/releases/download/v0.1/wxPython-4.2.2-cp311-cp311-linux_x86_64.whl

          python -m pip install -r requirements.txt

          python -m pip install pyinstaller

          echo "${{ env.pythonLocation }}\bin" >> $GITHUB_PATH
      - name: Tests
        shell: bash
        run: |
          pytest
      - shell: bash
        run: |
          make dist
        env:
          PLATFORM: linux
          INKSTITCH_GPG_KEY: ${{ secrets.INKSTITCH_GPG_KEY }}
      - uses: actions/upload-artifact@v7
        with:
          name: inkstitch-linux64
          path: artifacts
  linuxarm64:
    runs-on: ubuntu-22.04-arm
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - uses: actions/setup-python@v6
        with:
          python-version: '3.11.x'
          cache: 'pip'
      - name: install dependencies
        shell: bash
        run: |
          sudo apt-get update
          sudo gem install fpm
          python -m pip install --upgrade pip
          python -m pip install wheel

          sudo apt-get install gettext

          # for wxPython
          sudo apt install libnotify4
          sudo apt install glib-networking libsdl2-dev libsdl2-2.0-0

          # for PyGObject
          sudo apt install libgirepository1.0-dev libcairo2-dev

          # for shapely
          sudo apt install build-essential libgtk-3-dev cmake

          # for numpy
          sudo apt install  gfortran libopenblas-dev liblapack-dev pkg-config

          uname -a
          python --version
          python -m pip --version
          python -m pip debug

          python -m pip install pycairo
          python -m pip install PyGObject==3.50.0
          python -m pip install numpy --no-binary numpy
          python -m pip install wxPython==4.2.5 --no-binary wxPython

          python -m pip install -r requirements.txt

          python -m pip install pyinstaller

          echo "${{ env.pythonLocation }}\bin" >> $GITHUB_PATH
      - name: Tests
        shell: bash
        run: |
          pytest
      - shell: bash
        run: |
          make dist
        env:
          PLATFORM: linux
          INKSTITCH_GPG_KEY: ${{ secrets.INKSTITCH_GPG_KEY }}
      - uses: actions/upload-artifact@v7
        with:
          name: inkstitch-linuxarm64
          path: artifacts
  windows64:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - uses: actions/setup-python@v6
        with:
          python-version: '3.11.x'
          architecture: 'x64'
          cache: 'pip'
      - uses: microsoft/setup-msbuild@v3
      - name: Setup Git for Windows SDK
        uses: git-for-windows/setup-git-for-windows-sdk@v2
        with:
          flavor: build-installers
      - name: install dependencies
        shell: bash
        run: |
          git config --system core.longpaths true
          python -m pip install --upgrade pip
          python -m pip install wheel
          pip install wxPython==4.2.5

          python -m pip install -r requirements.txt

          python -m pip install pyinstaller

          echo "${{ env.pythonLocation }}\bin" >> $GITHUB_PATH
      - name: Tests
        shell: bash
        run: |
          pytest
      - shell: bash
        run: |
          make dist
        env:
          PLATFORM: windows
      - name: Set siging policy to release
        if: ${{ startsWith(github.event.ref, 'refs/tags/v') || inputs.TEST_SIGNING }}
        shell: bash
        run: |
          echo release_policy="release-signing" >> $GITHUB_ENV
      - name: upload-unsigned-exe
        if: ${{ startsWith(github.event.ref, 'refs/tags/v') || inputs.TEST_SIGNING }}
        id: upload-unsigned-exe
        uses: actions/upload-artifact@v7
        with:
          name: inkstitch-windows64-exe
          path: |
            dist/inkstitch/bin/inkstitch.exe
      - name: Sign-exe
        if: ${{ startsWith(github.event.ref, 'refs/tags/v') || inputs.TEST_SIGNING }}
        id: Sign-exe
        uses: signpath/github-action-submit-signing-request@v1.1
        with:
          api-token: '${{ secrets.SIGNPATH_API_TOKEN }}'
          organization-id: '6b880880-2af8-4cf3-a8e7-1b4977c593df'
          project-slug: 'inkstitch'
          signing-policy-slug: '${{ env.release_policy }}'
          github-artifact-id: '${{ steps.upload-unsigned-exe.outputs.artifact-id }}'
          wait-for-completion: true
          output-artifact-directory: 'signed-artifacts'
      - name: Copy signed exe to dist
        if: ${{ startsWith(github.event.ref, 'refs/tags/v') || inputs.TEST_SIGNING }}
        shell: bash
        run: |
            mv  -f signed-artifacts/inkstitch.exe dist/inkstitch/bin/inkstitch.exe
      - shell: bash
        run: |
          bash bin/build-windows-installer
        env:
          PLATFORM: windows
      - name: upload-unsigned-installer
        if: ${{ startsWith(github.event.ref, 'refs/tags/v') || inputs.TEST_SIGNING }}
        id: upload-unsigned-installer
        uses: actions/upload-artifact@v7
        with:
          name: inkstitch-windows64-installer
          path: signed-artifacts
      - name: Sign-installer
        if: ${{ startsWith(github.event.ref, 'refs/tags/v') || inputs.TEST_SIGNING }}
        id: Sign-installer
        uses: signpath/github-action-submit-signing-request@v1.1
        with:
          api-token: '${{ secrets.SIGNPATH_API_TOKEN }}'
          organization-id: '6b880880-2af8-4cf3-a8e7-1b4977c593df'
          project-slug: 'inkstitch'
          signing-policy-slug: '${{ env.release_policy }}'
          artifact-configuration-slug: 'windows-installer-config'
          github-artifact-id: '${{ steps.upload-unsigned-installer.outputs.artifact-id }}'
          wait-for-completion: true
          output-artifact-directory: 'signed-artifacts'
      - uses: actions/upload-artifact@v7
        with:
          name: inkstitch-windows64
          path: signed-artifacts
  macx86:
    runs-on: macos-15-intel
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - uses: actions/setup-python@v6
        with:
          python-version: '3.11.x'
          cache: 'pip'
      - name: install dependencies
        shell: bash
        run: |
          brew update

          brew install gtk+3 pkg-config gobject-introspection geos libffi gettext jq gnu-getopt libiconv || true

          # These exports of libiconv to build wxpython
          # inkscape libiconv has issues with wxpython pip wheel
          export PATH="/usr/local/opt/libiconv/bin:$PATH"
          export LDFLAGS="-L/usr/local/opt/libiconv/lib"
          export CPPFLAGS="-I/usr/local/opt/libiconv/include"

          export LDFLAGS="-L/usr/local/opt/libffi/lib"
          export PKG_CONFIG_PATH="/usr/local/opt/libffi/lib/pkgconfig"

          # for msgfmt
          echo "/usr/local/opt/gettext/bin" >> $GITHUB_PATH

          echo "GI_TYPELIB_PATH=/usr/local/lib/girepository-1.0/" >> $GITHUB_ENV

          pip install --upgrade pip
          pip --version
          pip install wheel
          pip install PyGObject
          pip install wxPython==4.2.5 --no-binary wxPython

          pip install -r requirements.txt

          pip install pyinstaller

          echo "${{ env.pythonLocation }}/bin" >> $GITHUB_PATH
      - name: Tests
        shell: bash
        run: |
          pytest
      - shell: bash
        run: |
          make dist
        env:
          PLATFORM: osx
          MACOS_CERTIFICATE: ${{ secrets.INKSTITCH_APPLE_DEVELOPER_CERTIFICATE }}
          MACOS_CERTIFICATE_PWD: ${{ secrets.INKSTITCH_APPLE_DEVELOPER_CERTIFICATE_PASSWORD }}
          KEYCHAIN_PWD: ${{ secrets.KEYCHAIN_PASSWORD }}
          INSTALLER_CERTIFICATE: ${{ secrets.INKSTITCH_APPLE_INSTALLER_CERTIFICATE }}
          INSTALLER_PWD: ${{ secrets.INKSTITCH_APPLE_INSTALLER_CERTIFICATE_PASSWORD }}
          NOTARY_ACCOUNT: ${{ secrets.INKSTITCH_NOTARIZE_AC }}
          NOTARY_PASSWORD: ${{ secrets.INKSTITCH_NOTARIZE_PASS }}

      - uses: actions/upload-artifact@v7
        with:
          name: inkstitch-mac-x86
          path: artifacts
  macarm64:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - uses: actions/setup-python@v6
        with:
          python-version: '3.11.x'
          cache: 'pip'
      - name: install dependencies
        shell: bash
        run: |
          brew update

          brew install gtk+3 pkg-config gobject-introspection geos libffi gettext jq gnu-getopt libiconv || true

          # These exports of libiconv to build wxpython
          # inkscape libiconv has issues with wxpython pip wheel
          export PATH="/opt/homebrew/opt/libiconv/bin:$PATH"
          export LDFLAGS="-L/opt/homebrew/opt/libiconv/lib"
          export CPPFLAGS="-I/opt/homebrew/opt/libiconv/include"

          export LDFLAGS="-L/opt/homebrew/opt/libffi/lib"
          export PKG_CONFIG_PATH="/opt/homebrew/opt/libffi/lib/pkgconfig"

          # for msgfmt
          echo "/opt/homebrew/opt/gettext/bin" >> $GITHUB_PATH

          echo "GI_TYPELIB_PATH=/opt/homebrew/lib/girepository-1.0/" >> $GITHUB_ENV

          pip install --upgrade pip
          pip --version
          pip install wheel
          pip install PyGObject
          pip install wxPython==4.2.5 --no-binary wxPython

          pip install -r requirements.txt

          pip install pyinstaller

          echo "${{ env.pythonLocation }}/bin" >> $GITHUB_PATH
      - name: Tests
        shell: bash
        run: |
          pytest
      - shell: bash
        run: |
          make dist
        env:
          PLATFORM: osx
          MACOS_CERTIFICATE: ${{ secrets.INKSTITCH_APPLE_DEVELOPER_CERTIFICATE }}
          MACOS_CERTIFICATE_PWD: ${{ secrets.INKSTITCH_APPLE_DEVELOPER_CERTIFICATE_PASSWORD }}
          KEYCHAIN_PWD: ${{ secrets.KEYCHAIN_PASSWORD }}
          INSTALLER_CERTIFICATE: ${{ secrets.INKSTITCH_APPLE_INSTALLER_CERTIFICATE }}
          INSTALLER_PWD: ${{ secrets.INKSTITCH_APPLE_INSTALLER_CERTIFICATE_PASSWORD }}
          NOTARY_ACCOUNT: ${{ secrets.INKSTITCH_NOTARIZE_AC }}
          NOTARY_PASSWORD: ${{ secrets.INKSTITCH_NOTARIZE_PASS }}

      - uses: actions/upload-artifact@v7
        with:
          name: inkstitch-mac-arm64
          path: artifacts

  release:
    runs-on: ubuntu-latest
    needs: [linux64, linuxarm64, windows64, macx86, macarm64]
    if: always()
    steps:
      - name: determine release info
        shell: bash
        run: |
          if [[ "${GITHUB_REF}" =~ ^refs/tags/v[0-9.]+$ ]]; then
            tag="${GITHUB_REF#refs/tags/}"
            echo "release_tag=${tag}" >> $GITHUB_ENV
            echo "prerelease=false" >> $GITHUB_ENV
            echo "title=${tag}" >> $GITHUB_ENV
          else
            branch="${GITHUB_REF#refs/heads/}"
            tag="dev-build-$(echo $branch | tr / -)"
            echo "release_tag=${tag}" >> $GITHUB_ENV
            echo "prerelease=true" >> $GITHUB_ENV
            echo "title=development build of $branch" >> $GITHUB_ENV
          fi
      - name: download linux64
        uses: actions/download-artifact@v8
        with:
          name: 'inkstitch-linux64'
          path: 'artifacts/'
      - name: download linuxarm64
        uses: actions/download-artifact@v8
        with:
          name: 'inkstitch-linuxarm64'
          path: 'artifacts/'
      - name: download windows64
        uses: actions/download-artifact@v8
        with:
          name: 'inkstitch-windows64'
          path: 'signed-artifacts/'
        if: always()
      - name: download macx86
        uses: actions/download-artifact@v8
        with:
          name: 'inkstitch-mac-x86'
          path: 'artifacts/'
        if: always()
      - name: download macarm64
        uses: actions/download-artifact@v8
        with:
          name: 'inkstitch-mac-arm64'
          path: 'artifacts/'
        if: always()
      - name: create/update release
        uses: softprops/action-gh-release@v3
        if: always()
        with:
          token: "${{secrets.GITHUB_TOKEN}}"
          tag_name: "${{env.release_tag}}"
          prerelease: "${{env.prerelease}}"
          name: "${{env.title}}"
          files: |
            artifacts/*.exe
            artifacts/*.pkg
            artifacts/*.deb
            artifacts/*.rpm
            artifacts/*.tar.xz
            artifacts/*.sh
            artifacts/*.zip
            signed-artifacts/*.exe
            signed-artifacts/*.zip
