
# Action description:
#   https://docs.github.com/en/actions

name: UV Build

# when the workflow should run
on:
  push: # at least ones must be triggered by a push to be available for manual trigger
    tags:
      - 'build*'

    # branches:
    #   - missing/*  # branch pattern **= any number of characters and /, * = any number of characters not including /

  workflow_dispatch:  # manual trigger of the workflow
    inputs:
      # input variables for manual run
      build_type:                   # access: github.event.inputs.build_type
        description: 'Build type'
        required: true
        default: 'linux64'  # default value
        type: choice  # type of the input, can be number, boolean, string, choice or environment
        options:
          - linux64
          # - linux32
          - linux-arm64
          # - linux-arm32

          # - windows64
          # - windows32
          # - windows-arm64
          # - windows-arm32

          # - macos64
          # - macos32
          # - macos-arm64
          # - macos-arm32

          - all

      break_on:                  # access: github.event.inputs.break_on
        description: 'Stop the build immediately at a predefined location.'
        required: true
        default: no  # default value
        type: choice  # type of the input, can be number, boolean, string, choice or environment
        options:
          - no    # normal build
          - uv    # stop the build at the uv venv creation step


# working example: ----------------------------------------------------------
jobs:
  prepare_build:
    runs-on: ubuntu-latest
    outputs:
      # Define outputs that will be available for other jobs
      final_build_type: ${{ steps.set_vars.outputs.calculated_build_type }}
      final_break_on: ${{ steps.set_vars.outputs.calculated_break_on }}
    steps:
      - name: Set default build variables for Push event
        id: set_vars # Important for referencing the outputs of this step
        run: |

          echo "input variables:"
          echo "Build Type: ${{ github.event.inputs.build_type }}"
          echo "Break On: ${{ github.event.inputs.break_on }}"
          echo "Event Name: ${{ github.event_name }}"

          # Check if the event is a workflow_dispatch (manual trigger) or push
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
              # If so, use the values from the inputs
            CALCULATED_BUILD_TYPE="${{ github.event.inputs.build_type }}"
            CALCULATED_BREAK_ON="${{ github.event.inputs.break_on }}"
          else
            # If not (i.e. it's a push or other event), use the defaults
            CALCULATED_BUILD_TYPE="linux64"
            CALCULATED_BREAK_ON="uv"
          fi

          echo "Calculated Build Type: $CALCULATED_BUILD_TYPE"
          echo "Calculated Stop Value: $CALCULATED_BREAK_ON"

          # Set the outputs for this step
          echo "calculated_build_type=${CALCULATED_BUILD_TYPE}" >> "$GITHUB_OUTPUT"
          echo "calculated_break_on=${CALCULATED_BREAK_ON}" >> "$GITHUB_OUTPUT"


  call_linux64_build:
    needs: prepare_build # this job depends on the prepare_build job
    if: >
      needs.prepare_build.outputs.final_build_type == 'linux64' ||
      needs.prepare_build.outputs.final_build_type == 'all'
    name: Build Linux64
    # - uses with reusable must be on job level, not on step level
    # - .yml must be on top level of .github/workflows/
    uses: ./.github/workflows/uv_build_linux64.yml # call reusable workflow
    with:
      break_on: ${{ needs.prepare_build.outputs.final_break_on }} # set input variable for the reusable workflow


  call_linux_arm64_build:
    needs: prepare_build # this job depends on the prepare_build job
    if: >
      needs.prepare_build.outputs.final_build_type == 'linux-arm64' ||
      needs.prepare_build.outputs.final_build_type == 'all'
    name: Build Linux-arm64
    uses: ./.github/workflows/uv_build_linux-arm64.yml # call reusable workflow
    with:
      break_on: ${{ needs.prepare_build.outputs.final_break_on }} # set input variable for the reusable workflow
#----------------------------------------------------
