
# Action description:
#   https://docs.github.com/en/actions

name: UV Build

# when the workflow should run
on:
  push: # at least ones must be triggered by a push to be available for manual trigger
    branches:
      - missing/*  # branch pattern **= any number of characters and /, * = any number of characters not including /
  workflow_dispatch:  # manual trigger of the workflow
    inputs:
      # input variables for manual run
      build_type:
        description: 'Build type'
        required: true
        default: 'linux64'  # default value
        type: choice  # type of the input, can be number, boolean, string, choice or environment
        options:
          - linux64
          # - linux32
          - linux-arm64
          # - linux-arm32

          # - windows64
          # - windows32
          # - windows-arm64
          # - windows-arm32

          # - macos64
          # - macos32
          # - macos-arm64
          # - macos-arm32

          - all

      build_data:
        description: 'Debug mode'
        required: false
        default: 'exit_on_uv'  # default value
        type: choice  # type of the input, can be number, boolean, string, choice or environment
        options:
          - none
          - exit_on_uv


# working example: ----------------------------------------------------------
jobs:
  call_linux64_build:
    if: >
      github.event.inputs.build_type == 'linux64' ||
      github.event.inputs.build_type == 'all'
    name: Build (${{ github.event.inputs.build_type }})
    # - uses with reusable must be on job level, not on step level
    # - .yml must be on top level of .github/workflows/
    uses: ./.github/workflows/uv_build_linux64.yml # call reusable workflow
    with:
      build_data: ${{ github.event.inputs.build_data }} # set input variable for the reusable workflow

  call_linux_arm64_build:
    if: ( github.event.inputs.build_type == 'linux-arm64' || github.event.inputs.build_type == 'all' )
    name: Build (${{ github.event.inputs.build_type }})
    uses: ./.github/workflows/uv_build_linux_arm64.yml # call reusable workflow
    with:
      build_data: ${{ github.event.inputs.build_data }} # set input variable for the reusable workflow
#----------------------------------------------------
