# .github/workflows/uv_build.yml
name: UV Linux

# when the workflow should run
on:
  push:
    branches:
      - kgn/*   # branch pattern **= any number of characters and /, * = any number of characters not including /
  workflow_dispatch:  # manual trigger of the workflow
    inputs:
      # input variables for manual run
      build_type:
        description: 'Build type'
        required: true
        default: 'linux64'  # default value
        type: choice
        options:
          - linux64
          - linux32
          - windows64
          - windows32
          - macos64
          - macos32

          - linux-arm64
          - linux-arm32
          - windows-arm64
          - windows-arm32
          - macos-arm64
          - macos-arm32

jobs:
  call_linux_build:
    if: startsWith(github.event.inputs.build_type, 'linux')
    # if: github.event.inputs.build_type == 'linux64' || github.event.inputs.build_type == 'linux32' || github.event.inputs.build_type == 'linux-arm64' || github.event.inputs.build_type == 'linux-arm32'
    name: Build Linux (${{ github.event.inputs.build_type }})
    uses: ./.github/workflows/uv_linux.yml # call reusable workflow
    # with:
    #   os_version: ${{ github.event.inputs.build_type || 'linux64' }}
      # custom_message: ${{ github.event.inputs.custom_pipeline_message }}
