
# Action description:
#   https://docs.github.com/en/actions

name: UV Build

# when the workflow should run
on:
  push: # at least ones must be triggered by a push to be available for manual trigger
    tags:
      - 'build*'  # unsigned build
      - 'v*.*.*'  # signed build
    # branches:
    #   - missing/*  # branch pattern **= any number of characters and /, * = any number of characters not including /

  workflow_dispatch:  # manual trigger of the workflow
    inputs:
      # input variables for manual run
      build_type:                   # ref: github.event.inputs.build_type | inputs.build_type
        description: 'Build type'
        required: true
        default: 'linux64'  # default value
        type: choice  # type of the input, can be number, boolean, string, choice or environment
        options:
          - linux64
          # - linux32
          - linux-arm64
          # - linux-arm32

          - windows64
          # - windows32
          # - windows-arm64
          # - windows-arm32

          # - darwin64
          # - darwin32
          # - darwin-arm64
          # - darwin-arm32

          # - macos64
          # - macos32
          # - macos-arm64
          # - macos-arm32

          - all

      sign_artifacts: # ref: github.event.inputs.sign_artifacts | inputs.sign_artifacts
        description: 'Digitally sign the generated build artifacts (requires signing credentials).'
        required: true
        default: 'no'  # default value
        type: choice
        options:
          - 'yes' # Sign all generated artifacts
          - 'no'  # Skip digital signing


      break_on:     # ref: github.event.inputs.break_on | inputs.break_on
        description: 'Stop the build immediately at a predefined location.'
        required: true
        default: 'no'  # default value
        type: choice  # type of the input, can be number, boolean, string, choice or environment
        options:
          - 'no'    # normal build
          - 'uv'    # stop the build at the uv venv creation step


# working example: ----------------------------------------------------------
jobs:
  # https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/accessing-contextual-information-about-workflow-runs#context-availability
  dump_contexts_to_log:
      runs-on: ubuntu-latest
      steps:
        - name: Dump environment variables
          run: printenv    # or just `env` to print all environment variables

        - name: Dump GitHub context (github...)
          env:
            GITHUB_CONTEXT: ${{ toJson(github) }}   # set the environment variable GITHUB_CONTEXT to the JSON representation of the github context
          run: echo "$GITHUB_CONTEXT"

        - name: Dump job context (job...)
          env:
            JOB_CONTEXT: ${{ toJson(job) }}
          run: echo "$JOB_CONTEXT"

        - name: Dump steps context (steps...)
          env:
            STEPS_CONTEXT: ${{ toJson(steps) }}
          run: echo "$STEPS_CONTEXT"

        - name: Dump runner context (runner...)
          env:
            RUNNER_CONTEXT: ${{ toJson(runner) }}
          run: echo "$RUNNER_CONTEXT"

        - name: Dump strategy context (strategy...)
          env:
            STRATEGY_CONTEXT: ${{ toJson(strategy) }}
          run: echo "$STRATEGY_CONTEXT"

        - name: Dump matrix context
          env:
            MATRIX_CONTEXT: ${{ toJson(matrix) }}
          run: echo "$MATRIX_CONTEXT"


# ---------------------------------------------------------------------------
  prepare_build:
    runs-on: ubuntu-latest
    outputs:
      # Define outputs that will be available for other jobs
      #  - we cannot globbaly overwrite environment variables, so we use outputs
      #    ref: needs.prepare_build.outputs.build_type
      build_type: ${{ steps.set_vars.outputs.build_type }}
      sign_artifacts: ${{ steps.set_vars.outputs.sign_artifacts }}
      break_on: ${{ steps.set_vars.outputs.break_on }}
    steps:
      - name: Set default build variables for Push event
        id: set_vars # Important for referencing the outputs of this step
        run: |

          # Info
          echo "Input Variables (github.event.inputs):"
          echo "  Build Type: ${{ github.event.inputs.build_type }}"
          echo "  Sign Artifacts: ${{ github.event.inputs.sign_artifacts }}"
          echo "  Break On: ${{ github.event.inputs.break_on }}"


          # Check if the event is a workflow_dispatch (manual trigger) or push
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
              # If so, use the values from the inputs
            MY_BUILD_TYPE="${{ github.event.inputs.build_type }}"
            MY_BREAK_ON="${{ github.event.inputs.break_on }}"
            MY_SIGN_ARTIFACTS="${{ github.event.inputs.sign_artifacts }}"

          else

            # If not (i.e. it's a push or other event), use the defaults
            MY_BUILD_TYPE="linux64"   # all
            MY_BREAK_ON="uv"          # no

            # only set if tag is v*.*.*
            if [[ "${{ github.event_name }}" == "push" &&
                  startsWith(github.ref, 'refs/tags/v') ]]; then
              # If the event is a push to a tag starting with 'v', set sign_artifacts to 'yes'
              MY_SIGN_ARTIFACTS="yes"   # yes
            else
              # Otherwise, set sign_artifacts to 'no'
              MY_SIGN_ARTIFACTS="no"    # no
            fi

          fi

          echo "My Build Type: $MY_BUILD_TYPE"
          echo "My Stop Value: $MY_BREAK_ON"
          echo "My Sign Artifacts: $MY_SIGN_ARTIFACTS"

          # Set the outputs for this step
          echo "build_type=${MY_BUILD_TYPE}" >> "$GITHUB_OUTPUT"
          echo "break_on=${MY_BREAK_ON}" >> "$GITHUB_OUTPUT"
          echo "sign_artifacts=${MY_SIGN_ARTIFACTS}" >> "$GITHUB_OUTPUT"


  call_linux64_build:
    needs: prepare_build # this job depends on the prepare_build job
    if: >
      needs.prepare_build.outputs.build_type == 'linux64' ||
      needs.prepare_build.outputs.build_type == 'all'
    name: Build Linux64
    # - uses with reusable must be on job level, not on step level
    # - .yml must be on top level of .github/workflows/
    uses: ./.github/workflows/uv_build_linux64.yml # call reusable workflow
    with:
      build_type: ${{ needs.prepare_build.outputs.build_type }} # set input variable for the reusable workflow
      sign_artifacts: ${{ needs.prepare_build.outputs.sign_artifacts }}


  call_linux_arm64_build:
    needs: prepare_build # this job depends on the prepare_build job
    if: >
      needs.prepare_build.outputs.build_type == 'linux-arm64' ||
      needs.prepare_build.outputs.build_type == 'all'
    name: Build Linux-arm64
    uses: ./.github/workflows/uv_build_linux-arm64.yml # call reusable workflow
    with:
      break_on: ${{ needs.prepare_build.outputs.break_on }} # set input variable for the reusable workflow
      sign_artifacts: ${{ needs.prepare_build.outputs.sign_artifacts }}


  call_windows64_build:
    needs: prepare_build # this job depends on the prepare_build job
    if: >
      needs.prepare_build.outputs.build_type == 'windows64' ||
      needs.prepare_build.outputs.build_type == 'all'
    name: Build Windows64
    uses: ./.github/workflows/uv_build_windows64.yml # call reusable workflow
    with:
      break_on: ${{ needs.prepare_build.outputs.break_on }} # set input variable for the reusable workflow
      sign_artifacts: ${{ needs.prepare_build.outputs.sign_artifacts }}


#----------------------------------------------------
