
name: UV Linux32 build

# when the workflow should run
on:
  workflow_call:  # manual trigger of the workflow
    inputs:

      break_on: # ref: inputs.break_on
        description:  'Stop the build immediately at a predefined location.'
        required: true
        default: 'no'    # default value
        type: string  # type of the input, can be string, boolean, or number

      self_signed:
        description: 'Sign on the fly'
        required: true
        default: true
        type: string

    secrets:  # secrets that are required for the workflow, otherwise are not available
      INKSTITCH_GPG_KEY:
        required: true

# Jobs are steps that run on the same runner
jobs:
  linux32:  # name of the job
    env:
      MY_BREAK_ON: ${{ github.event.inputs.break_on }}
      MY_SELF_SIGNED: ${{ github.event.inputs.self_signed }}

    # Node required for actions, install follows
    # https://github.com/actions/upload-artifact/issues/616
    runs-on: ubuntu-latest
    container:
      image: linuxmintd/lmde6-i386  # Linux Mint Debian Edition 6 (LMDE6) i386
      volumes:
      - ${{ github.workspace }}:/__e/node20  # mount the workspace to the container

    steps:
      - name: Download & setup Node
        shell: bash
        run: |

          ls -lar /__e/node20      # check if the directory is empty
          apt-get update
          apt-get install -y curl  # we need curl to download node.js
          curl -Lo /tmp/node.tar.gz https://unofficial-builds.nodejs.org/download/release/v20.17.0/node-v20.17.0-linux-x86.tar.gz
          cd /__e/node20           # change to the mounted workspace directory
          tar -x --strip-components=1 -f /tmp/node.tar.gz # extract the node.js archive


      - name: Download Inkstitch # Download the source code, no submodules
        uses: actions/checkout@v4

      - name: Install uv  # https://docs.astral.sh/uv/guides/integration/github/
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true



