
name: UV Linux64 build

# when the workflow should run
on:
  workflow_call:  # manual trigger of the workflow
    inputs:
      stop_value:  # access: inputs.stop_value
        description: 'Stop value for the build, 0 to continue, !=0 to stop'
        required: true
        default: 1    # default value
        type: number  # type of the input, can be string, boolean, or number


# Jobs are steps that run on the same runner
jobs:
  linux64:  # name of the job
    # define the OS of the runner
    runs-on: ubuntu-22.04

    # steps are a sequence of commands that will be executed
    steps:
      - name: Download Inkstitch # Download the source code, no submodules
        uses: actions/checkout@v4

      - name: Install uv  # https://docs.astral.sh/uv/guides/integration/github/
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Setup environment
        shell: bash
        run: |  # working directory is the root of the inkstitch repo

          # input data
          echo "Build data 1: ${{ github.event.inputs.stop_value }}"
          echo "Build data 2: ${{ inputs.stop_value }}"

          uv python list
          uv python pin 311  # pin to local python version
          uv venv  # create a virtual environment with the pinned python version

          if (( ${{ inputs.stop_value }} > 0 )); then
            echo "Stopping on request"
            exit 1
          fi

          exit 1

          # install system dependencies
          sudo apt-get update  # update package list

          sudo gem install fpm # install fpm for packaging (Ruby gems)
          sudo apt-get install gettext # install gettext for translations (.po msgfmt)

          # for PyGObject 3.50 to compile
          sudo apt install libgirepository1.0-dev libcairo2-dev

          # for wxPython run
          sudo apt install libnotify4
          sudo apt install glib-networking libsdl2-2.0-0 # libsdl2-dev

          # for shapely & wxPython compile
          # sudo apt install build-essential libgtk-3-dev # cmake - use uv to install cmake

          bin/uv/generate_pyproject.sh # generate pyproject.toml from uv config

          # debug
          cat /etc/os-release
          cat pyproject.toml

          uv sync # install dependencies from pyproject.toml

          # . .venv/bin/activate  # activate the virtual environment
          # type python

          echo "pythonLocation: ${{ env.pythonLocation }}"  # empty - what is this good for
          echo "GITHUB_PATH: $GITHUB_PATH"

      - name: Build dist
        shell: bash
        run: |

          . .venv/bin/activate  # activate the virtual environment
          type python  # check python version
          # python --version

          make dist
        env:
          BUILD: linux
          # secrets are available only in main branch
          INKSTITCH_GPG_KEY: ${{ secrets.INKSTITCH_GPG_KEY }}

      # save the build artifacts for later use by other jobs
      - uses: actions/upload-artifact@v4
        with:
          name: inkstitch-linux64
          path: artifacts

