
name: UV On Test

on:
  push:
    tags: # valid only for the HEAD of the repository
      - 'on-test*' # run workflow on tags that start with 'on-test'"

  workflow_dispatch:  # manual trigger of the workflow
    inputs:
      message: # ref: inputs.message
        description: 'A custom message to display'
        required: false
        default: 'Hello from manual trigger!'
        type: string


# global variables:
env:
  MY_GLOBAL_VAR: 'value of MY_GLOBAL_VAR'

jobs:
  job1:
    name: Job1 name
    runs-on: ubuntu-latest
    env:
      MY_JOB1: "value of MY_JOB1"  # job-level environment variable, accessible in all steps of this job
      # MY_GLOBAL_VAR: "overridden value of MY_GLOBAL_VAR"  # override global variable in this job

    steps:
      - name: Step1 name
        id: step1
        shell: bash
        run: |  # run

          echo "${{ toJSON(github.event.inputs) }}"
          echo "MY_GLOBAL_VAR: $MY_GLOBAL_VAR"  # access global variable in env

          echo "MY_MSG=${{ github.event.inputs.message }}" >> $GITHUB_ENV # set env var accessible in subsequent steps
          echo "MY_JOB1="overridden MY_JOB1" >> $GITHUB_ENV
          printenv


      - name: Step2 name
        id: step2
        run: |

          echo "MY_GLOBAL_VAR: $MY_GLOBAL_VAR"
          env

  job2:
    needs: job1
    name: job2 name
    runs-on: ubuntu-latest
    steps:
      - name: Step1 name
        id: step1
        shell: bash
        run: |

          echo "${{ toJSON(github.event.inputs) }}"
          printenv
