
name: UV On Test

on:
  push:
    tags:
      - 'build*' # run workflow on tags that start with "build like "build-1.0", "build_featureX", "build/v2.0"


  # push:
  #   branches:
  #     - kgn/*   # branch pattern **= any number of characters and /, * = any number of characters not including /

  # workflow_dispatch:
    # You can optionally define inputs here if you need them.
    # For a very simple trigger, you might not need any.
    # inputs:
    #   message:
    #     description: 'A custom message'
    #     required: false
    #     default: 'Hello from manual trigger!'
    #     type: string

jobs:
  simple_job:
    runs-on: ubuntu-latest
    steps:
      - name: Greet the world
        run: |
          echo "This workflow was triggered !"
          echo "Current time is $(date)"
          # If you had inputs, you could access them like this:
          # echo "Custom message: ${{ github.event.inputs.message }}"