
name: UV On Test

on:
  push:
    tags: # valid only for the HEAD of the repository
      - 'on-test*' # run workflow on tags that start with 'on-test'"

  workflow_dispatch:  # manual trigger of the workflow
    inputs:
      message: # ref: inputs.message
        description: 'A custom message to display'
        required: false
        default: 'Hello from manual trigger!'
        type: string


# global variables:
env:
  MY_GLOBAL_VAR: 'value of MY_GLOBAL_VAR'

jobs:
  job1:
    name: Job1 name
    runs-on: ubuntu-latest
    steps:
      - name: Step1 name
        id: step1
        shell: bash
        run: |  # run

          # data from inputs
          echo "Step1 ..."
          echo "MY_GLOBAL_VAR: $MY_GLOBAL_VAR"
          # echo "MY_GLOBAL_VAR=${MY_GLOBAL_VAR}" >> $GITHUB_ENV
          echo "Custom message: ${{ github.event.inputs.message }}" >> $GITHUB_ENV
          printenv

      - name: Step2 name
        id: step2
        run: |

          echo "Global variable value: $MY_GLOBAL_VAR"
          # env
